config/routes.rb
Rails.application.routes.draw do
  namespace :site do
    get 'welcome/index'
  end
  namespace :users_backoffice do
    get 'welcome/index'
    get 'profile', to: 'profile#edit'
    patch 'profile', to: 'profile#update'
  end
  namespace :admins_backoffice do
    get 'welcome/index'
    resources :admins
  end
  devise_for :users
  devise_for :admins
  
  root to: 'site/welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bank_datum.rb
class BankDatum < ApplicationRecord
  belongs_to :user
end

app/models/business_address.rb
class BusinessAddress < ApplicationRecord
  belongs_to :user
end

app/models/contract.rb
class Contract < ApplicationRecord
has_one :user
has_one :representative
end

app/models/dependent.rb
class Dependent < ApplicationRecord
  belongs_to :user
end

app/models/home_address.rb
class HomeAddress < ApplicationRecord
  belongs_to :user
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :user
end

app/models/representative.rb
class Representative < ApplicationRecord
  belongs_to :contract
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :contract
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Validations
  validates :first_name, presence: true, length: {minimum: 3}
  validates :last_name, presence: true, length: {minimum: 3}
  
  # Virtual_Attributes
  def full_name
    [self.first_name, self.last_name].join(' ')
  end
end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
  belongs_to :user
end

app/controllers/admins_backoffice/admins_controller.rb
class AdminsBackoffice::AdminsController < AdminsBackofficeController
  before_action :verify_password, only: [:update]
  before_action :set_admin, only: [:edit, :update, :destroy]
  before_action :get_admins, only: [:index, :new, :edit]
  
  def index
  end

  def new
    @admin = Admin.new
  end

  def create
    @admin = Admin.new(params_admin)
    if @admin.save
      redirect_to admins_backoffice_admins_path, notice: "Admin #{@admin.email} Cadastrado com Sucesso!"       
    else
      render :new
    end
  end

  def edit 
  end

  def update
    if @admin.update(params_admin)
      #AdminMailer.update_email(current_admin, @admin).deliver_now
      redirect_to admins_backoffice_admins_path, notice: "Admin #{@admin.email} Atualizado com Sucesso!"       
    else
      render :edit
    end
  end

    def destroy
      if @admin.destroy
        redirect_to admins_backoffice_admins_path, notice: "Admin #{@admin.email} Removido com Sucesso!"       
      else
        render :index
      end
    end

  private
  def verify_password
    if params[:admin] [:password].blank? && params[:admin] [:password_confirmation].blank?
      params[:admin].extract!(:password, :password_confirmation)
    end
  end
  
  def set_admin
    @admin = Admin.find(params[:id])
  end
  
  def get_admins
    @admins = Admin.all
  end
  
  def params_admin
    params.require(:admin).permit(:email, :password, :password_confirmation)
  end
end

app/controllers/admins_backoffice/welcome_controller.rb
class AdminsBackoffice::WelcomeController < AdminsBackofficeController
  def index
  end
end

app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
  before_action :authenticate_admin!
  layout 'admins_backoffice'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout :layout_by_resource

protected

  def layout_by_resource
    devise_controller? ? "#{resource_class.to_s.downcase}_devise" : "application"
  end
end

app/controllers/site/welcome_controller.rb
class Site::WelcomeController < SiteController
  def index
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  layout 'site'
end

app/controllers/users_backoffice_controller.rb
class UsersBackofficeController < ApplicationController
  before_action :authenticate_user!
  layout 'users_backoffice'
end

app/helpers/admins_backoffice/admins_helper.rb
module AdminsBackoffice::AdminsHelper
end

app/helpers/admins_backoffice/welcome_helper.rb
module AdminsBackoffice::WelcomeHelper
end

app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper

  def translate_method(object = nil, method = nil)
    if object && method
      object.model.human_attribute_name(method)
    else
      "Error_Message"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/site/welcome_helper.rb
module Site::WelcomeHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_backoffice/profile_helper.rb
module UsersBackoffice::ProfileHelper
end

app/helpers/users_backoffice_helper.rb
module UsersBackofficeHelper
end

app/views/admins_backoffice/admins/edit.html.erb
<%= render partial: 'admins_backoffice/admins/shared/form',
locals: { action_message: t('headers.editing', model: @admin.model_name.human)} %>

app/views/admins_backoffice/admins/index.html.erb
    <!-- Begin Page Content -->
    <div class="container-fluid">
      <!-- DataTales Example -->
      <div class="card shadow mb-4">
        <div class="card-header py-3">
          <h6 class="m-0 font-weight-bold text-primary">DataTables Example</h6>
        </div>
        <div class="card-body">
          <div class="table-responsive">
            <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
              <thead>
                <tr>
                  <th><%= translate_method(@admins, :id) %></th>
                  <th>Name</th>
                  <th><%= translate_method(@admins, :email) %></th>
                  <th><%= link_to new_admins_backoffice_admin_path,
                  class:"btn btn-success btn-circle btn-sm" do %>
                  <i class="fas fa-plus-circle"></i>
                  <% end %>
                  </th>
                </tr>
              </thead>
              <tfoot>
                <tr>
                  <th><%= translate_method(@admins, :id) %></th>
                  <th>Name</th>
                  <th><%= translate_method(@admins, :email) %></th>
                  <th></th>
                </tr>
              </tfoot>
              <tbody>
                <% @admins.each do |admin| %>                    
                  <tr>
                    <td><%= admin.id %></td>
                    <td><%= admin.id %></td>
                    <td><%= admin.email %></td>
                    <td><%= link_to edit_admins_backoffice_admin_path(admin),
                    class:"btn btn-info btn-circle btn-sm" do %>
                     <i class="fas fa-user-edit"></i>
                    <% end %>
                    <%= link_to admins_backoffice_admin_path(admin), method: :delete,
                     class:"btn btn-danger btn-circle btn-sm", 
                      data: {confirm: t('messages.admin.confirm', item: admin.email)} do %>
                    <i class="fas fa-trash"></i>
                    <% end %>
                    </td>
                  </tr>
                <% end %>
              </tbody>
            </table>
          </div>
        </div>
      </div>
    </div>
    <!-- /.container-fluid -->
  <!-- End of Main Content -->
  <!-- Footer -->
  <footer class="sticky-footer bg-white">
    <div class="container my-auto">
      <div class="copyright text-center my-auto">
        <span>Copyright &copy; Your Website 2019</span>
      </div>
    </div>
  </footer>
  <!-- End of Footer -->
<!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>

<!-- Logout Modal-->
<div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
<div class="modal-dialog" role="document">
  <div class="modal-content">
    <div class="modal-header">
      <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
      <button class="close" type="button" data-dismiss="modal" aria-label="Close">
        <span aria-hidden="true">×</span>
      </button>
    </div>
    <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
    <div class="modal-footer">
      <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
      <a class="btn btn-primary" href="login.html">Logout</a>
    </div>
  </div>
</div>
</div>

app/views/admins_backoffice/admins/new.html.erb
<%= render partial: 'admins_backoffice/admins/shared/form',
locals: { action_message: t('headers.registering', model: @admin.model_name.human)} %>