config/routes.rb
Rails.application.routes.draw do
  namespace :site do
    get 'welcome/index'
  end
  namespace :users_backoffice do
    get 'welcome/index'
    get 'profile', to: 'profile#edit'
    patch 'profile', to: 'profile#update'
  end
  namespace :admins_backoffice do
    get 'welcome/index'
    resources :admins
  end
  devise_for :users
  devise_for :admins
  
  root to: 'site/welcome#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/bank_datum.rb
class BankDatum < ApplicationRecord
  belongs_to :user
end

app/models/business_address.rb
class BusinessAddress < ApplicationRecord
  belongs_to :user
end

app/models/contract.rb
class Contract < ApplicationRecord
has_one :user
has_one :representative
end

app/models/dependent.rb
class Dependent < ApplicationRecord
  belongs_to :user
end

app/models/home_address.rb
class HomeAddress < ApplicationRecord
  belongs_to :user
end

app/models/phone.rb
class Phone < ApplicationRecord
  belongs_to :user
end

app/models/representative.rb
class Representative < ApplicationRecord
  belongs_to :contract
end

app/models/user.rb
class User < ApplicationRecord
  belongs_to :contract
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  # Validations
  validates :first_name, presence: true, length: {minimum: 3}
  validates :last_name, presence: true, length: {minimum: 3}
  
  # Virtual_Attributes
  def full_name
    [self.first_name, self.last_name].join(' ')
  end
end

app/models/user_profile.rb
class UserProfile < ApplicationRecord
  belongs_to :user
end

app/controllers/admins_backoffice_controller.rb
class AdminsBackofficeController < ApplicationController
  before_action :authenticate_admin!
  layout 'admins_backoffice'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  layout :layout_by_resource

protected

  def layout_by_resource
    devise_controller? ? "#{resource_class.to_s.downcase}_devise" : "application"
  end
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  layout 'site'
end

app/controllers/users_backoffice_controller.rb
class UsersBackofficeController < ApplicationController
  before_action :authenticate_user!
  layout 'users_backoffice'
end

app/helpers/admins_backoffice_helper.rb
module AdminsBackofficeHelper

  def translate_method(object = nil, method = nil)
    if object && method
      object.model.human_attribute_name(method)
    else
      "Error_Message"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/site/welcome_helper.rb
module Site::WelcomeHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/helpers/users_backoffice_helper.rb
module UsersBackofficeHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/admins_backoffice/admins/shared/_form.html.erb
<% if @admin.errors.any?%>
    <div class="alert alert-danger alert-dismissible fade show" role="alert">
      <ul>
        <% @admin.errors.full_messages.each do |message| %>
          <li>
            <strong><%= message %></strong>
          </li>
        <% end %>
      </ul>
      <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </div>
  <% end %>

<div class="row justify-content-md-center">
  <div class="col-lg-10">
    <div class="card o-hidden border-0 shadow-lg my-5">
      <div class="card-body p-0">
        <!-- Nested Row within Card Body -->
        <div class="row justify-content-md-center">
          <div class="col-lg-6">
            <div class="p-5">
              <div class="text-center">
                <h1 class="h4 text-gray-900 mb-4"><%= "#{action_message}" %>
                <%= @admin.model_name.human %></h1>
              </div>
              <hr>
              <%= form_with(model: [:admins_backoffice, @admin ],
              local: true, html: { class: "user" }) do |form| %>
                <div class="form-group row">
                  <div class="col-sm-6 mb-3 mb-sm-0">
                    <input type="text" class="form-control form-control-user"
                    id="exampleFirstName" placeholder="First Name">
                  </div>
                  <div class="col-sm-6">
                    <input type="text" class="form-control form-control-user"
                    id="exampleLastName" placeholder="Last Name">
                  </div>
                </div>
                <div class="form-group">
                  <%= form.email_field :email, class:"form-control form-control-user",
                  id:"exampleInputEmail", placeholder: translate_method(@admins, :email) %>
                </div>
                <div class="form-group row">
                  <div class="col-sm-6 mb-3 mb-sm-0">
                    <%= form.password_field :password, class:"form-control form-control-user",
                    id:"exampleInputPassword", placeholder: translate_method(@admins, :password) %>
                  </div>
                  <div class="col-sm-6">
                    <%= form.password_field :password_confirmation, class:"form-control form-control-user",
                    id:"exampleRepeatPassword", placeholder: translate_method(@admins, :password_confirmation) %>
                  </div>
                </div>
                <div class="row justify-content-md-center">
                  <div class="col-lg-6">
                    <button type="submit" class="btn btn-primary btn-user btn-block">
                      <%= t('label.Submit') %></button>
                  </div>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/admins_backoffice.html.erb
<!DOCTYPE html>
<html lang="en">

  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">
    <title>ABRASPESP</title>
      <%= csrf_meta_tags %>
      <%= csp_meta_tag %>
      <%= stylesheet_link_tag 'application', 'admins_backoffice' %>
      <link href="https://fonts.googleapis.com/css?family=Nunito:200,200i,300,300i,400,400i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
  </head>

  <body id="page-top">
    <!-- Page Wrapper -->
    <div id="wrapper">
    <!-- Sidebar -->
      <ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
      <!-- Sidebar - Brand -->
      <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
        <div class="sidebar-brand-icon rotate-n-15">
          <i class="fas fa-laugh-wink"></i>
        </div>
        <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
      </a>
      <!-- Divider -->
      <hr class="sidebar-divider my-0">
      <!-- Nav Item - Dashboard -->
      <li class="nav-item">
        <%= link_to admins_backoffice_welcome_index_path, class:"nav-link" do %>
          <i class="fas fa-fw fa-tachometer-alt"></i>
          <span>Dashboard</span>
          <% end %>
      </li>
      <!-- Divider -->
      <hr class="sidebar-divider">
      <!-- Heading --> 
      <li class="nav-item">
        <%= link_to admins_backoffice_admins_path, class:"nav-link" do %>
          <i class="fas fa-fw fa-users"></i>
          <span>Administradores</span></a>
          <% end %>
      </li>
      <!-- Divider -->
      <hr class="sidebar-divider d-none d-md-block">
      <!-- Sidebar Toggler (Sidebar) -->
      <div class="text-center d-none d-md-inline">
        <button class="rounded-circle border-0" id="sidebarToggle"></button>
      </div>
    </ul>
    <!-- End of Sidebar -->
    <!-- Content Wrapper -->
    <div id="content-wrapper" class="d-flex flex-column">
      <!-- Main Content -->
      <div id="content">
        <!-- Topbar -->
        <nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">
          <!-- Sidebar Toggle (Topbar) -->
          <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
            <i class="fa fa-bars"></i>
          </button>
          <!-- Topbar Search -->
          <form class="d-none d-sm-inline-block form-inline mr-auto ml-md-3 my-2 my-md-0 mw-100 navbar-search">
            <div class="input-group">
              <input type="text" class="form-control bg-light border-0 small" placeholder="Search for..." aria-label="Search" aria-describedby="basic-addon2">
              <div class="input-group-append">
                <button class="btn btn-primary" type="button">
                  <i class="fas fa-search fa-sm"></i>
                </button>
              </div>
            </div>
          </form>
          <!-- Topbar Navbar -->
          <ul class="navbar-nav ml-auto">
            <!-- Nav Item - Search Dropdown (Visible Only XS) -->
            <li class="nav-item dropdown no-arrow d-sm-none">
              <a class="nav-link dropdown-toggle" href="#" id="searchDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <i class="fas fa-search fa-fw"></i>
              </a>
              <!-- Dropdown - Messages --> 
            </li>

            <div class="topbar-divider d-none d-sm-block"></div>

            <!-- Nav Item - User Information -->
            <li class="nav-item dropdown no-arrow">
              <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                <span class="mr-2 d-none d-lg-inline text-gray-600 small">Administrador</span>
                <%= image_tag 'eu.jpg', class:"img-profile rounded-circle" %>
              </a>
              <!-- Dropdown - User Information -->
              <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
                <a class="dropdown-item" href="#">
                  <i class="fas fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
                  Profile
                </a>
                <div class="dropdown-divider"></div>
                <a class="dropdown-item" href="#" data-toggle="modal" data-target="#logoutModal">
                  <i class="fas fa-sign-out-alt fa-sm fa-fw mr-2 text-gray-400"></i>
                  Logout
                </a>
              </div>
            </li>
          </ul>
        </nav>
        <!-- End of Topbar -->
        <!-- Begin Page Content -->
        <div class="container-fluid">
          <!-- Page Heading -->
          <h1 class="h3 mb-4 text-gray-800"></h1>
          <%= yield %>
        </div>
        <!-- /.container-fluid -->
      </div>
      <!-- End of Main Content -->
      <!-- Footer -->
      <footer class="sticky-footer bg-white">
        <div class="container my-auto">
          <div class="copyright text-center my-auto">
            <span>Copyright &copy; Your Website 2019</span>
          </div>
        </div>
      </footer>
      <!-- End of Footer -->
    </div>
    <!-- End of Content Wrapper -->
  </div>
  <!-- End of Page Wrapper -->
  <!-- Scroll to Top Button-->
  <a class="scroll-to-top rounded" href="#page-top">
    <i class="fas fa-angle-up"></i>
  </a>
  <!-- Logout Modal-->
  <div class="modal fade" id="logoutModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
    <div class="modal-dialog" role="document">
      <div class="modal-content">
        <div class="modal-header">
          <h5 class="modal-title" id="exampleModalLabel">Ready to Leave?</h5>
          <button class="close" type="button" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">×</span>
          </button>
        </div>
        <div class="modal-body">Select "Logout" below if you are ready to end your current session.</div>
        <div class="modal-footer">
          <button class="btn btn-secondary" type="button" data-dismiss="modal">Cancel</button>
          <%= link_to 'Logout', destroy_admin_session_path, method: :delete, class:"btn btn-primary"  %>
        </div>
      </div>
    </div>
  </div>

  <%= javascript_include_tag 'application', 'admins_backoffice' %>
  
  <% if notice %> 
      <%= javascript_tag do %>
        $.bootstrapGrowl('<%= notice %>', {
          type: 'success', // (null, 'info', 'danger', 'success')
          offset: {from: 'top', amount: 20}, // 'top', or 'bottom'
          align: 'center', // ('left', 'right', or 'center')
          width: 250, // (integer, or 'auto')
          delay: 4000, // Time while the message will be displayed. It's not equivalent to the *demo* timeOut!
          allow_dismiss: true, // If true then will display a cross to close the popup.
          stackup_spacing: 10 //
        });
      <% end %>
    <% end %>

    <% if alert %> 
      <%= javascript_tag do %>
        $.bootstrapGrowl('<%= alert %>', {
          type: 'danger', // (null, 'info', 'danger', 'success')
          offset: {from: 'top', amount: 20}, // 'top', or 'bottom'
          align: 'right', // ('left', 'right', or 'center')
          width: 250, // (integer, or 'auto')
          delay: 4000, // Time while the message will be displayed. It's not equivalent to the *demo* timeOut!
          allow_dismiss: true, // If true then will display a cross to close the popup.
          stackup_spacing: 10 //
        });
      <% end %>
    <% end %>

  </body>
</html>


app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ABRASPESP</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application' %>
    <%= javascript_include_tag 'application' %>
  </head>

  <body>
  <h1> Layout Application </h1>
    <%= yield %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
  </body>
</html>

app/views/layouts/site.html.erb
<!DOCTYPE html>
<html lang="pt-br">
  <head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>ABRASPESP</title>
     <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= favicon_link_tag asset_path('abraspesp.png') %>
    <meta name="keywords" content=""/>
    <meta name="description" content=""/>
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
  <![endif]-->
      <%= stylesheet_link_tag    'application' %>
      <%= stylesheet_link_tag    'site' %>
  </head>
  
  <body>
    <header id="topo">
      <nav id="menuTopo" class="h4">
        <div class="container-fluid">
          <ul class="nav nav-pills">
            <% unless user_signed_in? %>
              <li>
                <%= link_to t('label.Signin'), new_user_session_path %>
              </li>
              <li>
                <%= link_to t('label.Signup'), new_user_registration_path %>
              </li>
            <% else %>
              <li class="dropdown">
                <a class="dropdown-toggle" data-toggle="dropdown">
                  <i class="fa fa-user"> </i>
                    <%= current_user.email %> <span class="caret"> </span></a>
                  <ul class="dropdown-menu" role="menu">
                    <li>
                      <%= link_to users_backoffice_welcome_index_path do %>
                        <i class="fa fa-dashboard"> </i> <%= t('label.Dashboard') %>
                      <% end %>
                    </li>
                    <li class="divider"></li>
                    <li>
                      <%= link_to destroy_user_session_path, method: :delete do %>
                        <i class="fa fa-sign-out" ></i> <%= t('label.Signout') %>
                      <% end %>
                    </li>
                  </ul>
              </li>
            <% end %>
          </ul>
        </div>
      </nav>
      <div class="container">
        <h1 id="logo"><a href="http://www.abraspesp.com.br/">
          <%= image_tag 'logo.png' %></a>
        </h1>
      </div><!--FIM .container-->
    </header><!--FIM header-->  
      
      <section id="banner" class="semResutadosRotativo">
        <div id="carousel-example-generic" class="carousel slide carousel-fade" data-ride="carousel">
          <ol class="carousel-indicators">
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            <li data-target="#carousel-example-generic" data-slide-to="3"></li>
            <li data-target="#carousel-example-generic" data-slide-to="4"></li>
            <li data-target="#carousel-example-generic" data-slide-to="5"></li>
            <li data-target="#carousel-example-generic" data-slide-to="6"></li>
            <li data-target="#carousel-example-generic" data-slide-to="7"></li>
            <li data-target="#carousel-example-generic" data-slide-to="8"></li>
            <li data-target="#carousel-example-generic" data-slide-to="9"></li>
          </ol>
          <div class="carousel-inner">
            <div class="item active" style="background-image: url('/assets/01.jpg');">
              <%= image_tag '01.jpg', alt:"" %>
            </div>
            <div class="item" style="background-image: url('/assets/02.jpg');">
              <%= image_tag '02.jpg', alt:"" %>
            </div>
            <div class="item" style="background-image: url('/assets/03.jpg');">
              <%= image_tag '03.jpg', alt:"" %>
            </div>
            <div class="item" style="background-image: url('/assets/04.jpg');">
              <%= image_tag '04.jpg', alt:"" %>
            </div>
            <div class="item" style="background-image: url('/assets/05.jpg');">
              <%= image_tag '05.jpg', alt:"" %>
            </div>
            <div class="item" style="background-image: url('/assets/06.jpg');">
              <%= image_tag '06.jpg', alt:"" %>
            </div>
            <div class="item" style="background-image: url('/assets/07.jpg');">
              <%= image_tag '07.jpg', alt:"" %>
            </div>
            <div class="item" style="background-image: url('/assets/08.jpg');">
              <%= image_tag '08.jpg', alt:"" %>
            </div>
            <div class="item" style="background-image: url('/assets/09.jpg');">
              <%= image_tag '09.jpg', alt:"" %>
            </div>
            <div class="item" style="background-image: url('/assets/10.jpg');">
              <%= image_tag '10.jpg', alt:"" %>
            </div> 
          </div>        
        </div>
      </section>
      <!--FIM section (#banner)-->
      <section id="imageScroll">
        <div class="clearfix"></div>
      </section>
      <section id="menuCorpo">
        <div class="container">
          <%= link_to image_tag('associe.png', class:'btnassoc'), new_user_registration_path %>
            <h3 id="frase">E faça parte do marior clube de benefícios do Brasil.</h3>
        </div>
      </section>
      <section id="corpo" class="home">
      <%= yield %>
      </section>
    <footer id="rodape">
      <div class="container">
        <div class="media-container-row content text-white">
          <div class="col-12 col-md-3">
            <div class="media-wrap">
              <%= link_to image_tag('logo.png', size:"125x70"), "#" %>
            </div>
          </div>
            <div class="col-12 col-md-3 mbr-fonts-style display-7">
              <h5 class="pb-3">
                Endereço
              </h5>
              <p class="mbr-text">
                Rua: Frei Antônio de Pádua, 1020<br>
                Guanabara - Campinas/SP
              </p>
            </div>
            <div class="col-12 col-md-3 mbr-fonts-style display-7">
              <h5 class="pb-3">
                Copyright ©<span><strong> ABRASPESP </strong></span>2019
              </h5>
              Todos os direitos reservados.
            </div>
            <div class="col-12 col-md-3 mbr-fonts-style display-7">
              <h5 class="pb-3">
                Contatos
              </h5>
              <p class="mbr-text">
                Email: andreguia@hotmail.com<br>
                Fone: +55 (11) 9 4969 0036
              </p>
            </div> 
        </div>
      </div>
      <!--FIM .container-->
      <div class="clearfix"></div>
    </footer>
    <!--FIM footer (#rodape)-->

    <%= javascript_include_tag 'application' %>
    <%= javascript_include_tag 'site' %>
    
    <script type="text/javascript">
      $(document).ready(function() {
        $('#imageScroll').scrollingCarousel({
          autoScroll: true,
          autoScrollSpeed: 50000
        });
        $("a[href='"+window.location+"']").parents("li").addClass('ativo');
      });
    </script>

  </body>
</html>

app/views/layouts/users_backoffice.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>ABRASPESP - USER</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', 'users_backoffice' %>
  </head>

  <body class="nav-md">
    <div class="container body">
      <div class="main_container">
        <div class="col-md-3 left_col menu_fixed">
          <div class="left_col scroll-view">
            <div class="navbar nav_title" style="border: 0;">
            <%= link_to site_welcome_index_path do %>
            <%= image_tag('logo.png', size:"62x35") %>ABRASPESP
            </div><% end %>
            <div class="clearfix"></div>
            <!-- menu profile quick info -->
            <div class="profile clearfix">
              <div class="profile_pic">
                <%= image_tag 'img.jpg', alt:"...", class:"img-circle profile_img"  %>
              </div>
              <div class="profile_info">
                <span>Welcome,</span>
                <h2><%= current_user.first_name %></h2>
              </div>
            </div>
            <!-- /menu profile quick info -->
            <br />
            <!-- sidebar menu -->
            <div id="sidebar-menu" class="main_menu_side hidden-print main_menu">
              <div class="menu_section">
                <ul class="nav side-menu">
                  <li><%= link_to users_backoffice_welcome_index_path do %>
                    <i class="fa fa-dashboard"></i><%= t('label.Dashboard') %>
                  <% end %>
                  </li>
                  <li><%= link_to users_backoffice_profile_path do %>
                    <i class="fa fa-edit"></i><%= t('label.Edit') %> <%= t('label.Profile') %>
                  <% end %>              
              </div>  
            </div>
            <!-- /sidebar menu -->
            <!-- /menu footer buttons -->
            <div class="sidebar-footer hidden-small">
              <a data-toggle="tooltip" data-placement="top" title="Settings">
                <span class="glyphicon glyphicon-cog" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="FullScreen">
                <span class="glyphicon glyphicon-fullscreen" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="Lock">
                <span class="glyphicon glyphicon-eye-close" aria-hidden="true"></span>
              </a>
              <a data-toggle="tooltip" data-placement="top" title="Logout" href="login.html">
                <span class="glyphicon glyphicon-off" aria-hidden="true"></span>
              </a>
            </div>
            <!-- /menu footer buttons -->
          </div>
        </div>

        <!-- top navigation -->
        <div class="top_nav">
          <div class="nav_menu">
            <nav>
              <div class="nav toggle">
                <a id="menu_toggle"><i class="fa fa-bars"></i></a>
              </div>

              <ul class="nav navbar-nav navbar-right">
                <li class="">
                  <a href="javascript:;" class="user-profile dropdown-toggle" data-toggle="dropdown" aria-expanded="false">
                    <%= image_tag 'img.jpg', alt:""%>
                    <%= current_user.full_name %>
                    <span class=" fa fa-angle-down"></span>
                  </a>
                  <ul class="dropdown-menu dropdown-usermenu pull-right">
                    <li><a href="javascript:;"> Profile</a></li>
                    <li>
                     <%= link_to destroy_user_session_path, method: :delete do %>
                    <i class="fa fa-sign-out pull-right"></i>
                    <%= t('label.Signout') %>
                    <% end %> 
                    </li>
                  </ul>
                </li>
                </ul>
                </li>
              </ul>
            </nav>
          </div>
        </div>
        <!-- /top navigation -->
        <!-- page content -->
        <div class="right_col" role="main">
          <div class="">
            <div class="page-title">
              <%= yield %>
            </div>
          </div>
        </div>
        <!-- /page content -->

        <!-- footer content -->
        <footer>
          <div class="pull-right">
            Gentelella - Bootstrap Admin Template by <a href="https://colorlib.com">Colorlib</a>
          </div>
          <div class="clearfix"></div>
        </footer>
        <!-- /footer content -->
      </div>
    </div>

    <%= javascript_include_tag 'application', 'users_backoffice' %>

    <% if notice %> 
      <%= javascript_tag do %>
        $.bootstrapGrowl('<%= notice %>', {
          type: 'success', // (null, 'info', 'danger', 'success')
          offset: {from: 'top', amount: 20}, // 'top', or 'bottom'
          align: 'center', // ('left', 'right', or 'center')
          width: 250, // (integer, or 'auto')
          delay: 4000, // Time while the message will be displayed. It's not equivalent to the *demo* timeOut!
          allow_dismiss: true, // If true then will display a cross to close the popup.
          stackup_spacing: 10 //
        });
      <% end %>
    <% end %>

    <% if alert %> 
      <%= javascript_tag do %>
        $.bootstrapGrowl('<%= alert %>', {
          type: 'danger', // (null, 'info', 'danger', 'success')
          offset: {from: 'top', amount: 20}, // 'top', or 'bottom'
          align: 'right', // ('left', 'right', or 'center')
          width: 250, // (integer, or 'auto')
          delay: 4000, // Time while the message will be displayed. It's not equivalent to the *demo* timeOut!
          allow_dismiss: true, // If true then will display a cross to close the popup.
          stackup_spacing: 10 //
        });
      <% end %>
    <% end %>

  </body>
</html>